name: Publish stable release

on:
  push:
    tags:
      - 'v*.*.*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="tracking_chain-$tag"
          # Build everything
          cargo build --verbose
          # Pack files
          tar -czf "${release_name}.tar.gz" /home/runner/work/InkTrackingChain/InkTrackingChain/target/tracking_chain.wasm /home/runner/work/InkTrackingChain/InkTrackingChain/target/tracking_chain.json /home/runner/work/InkTrackingChain/InkTrackingChain/target/tracking_chain.contract
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tracking_chain*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
